/*
 * Funcionalidad: Mapa de errores de dominio
 * Descripción: Asocia cada clase de error de dominio con su código de estado HTTP para el filtro global
 * Versión: 1.16
 * Autor: Marcela Mazo Castro
 * Proyecto: VentyLab
 * Tesis: Desarrollo de una aplicación web para la enseñanza de mecánica ventilatoria que integre un sistema de retroalimentación usando modelos de lenguaje
 * Institución: Universidad del Valle
 * Contacto: marcela.mazo@correounivalle.edu.co
 */
import { HttpStatus } from "@nestjs/common";

import { AIGenerationFailedError } from "@/common/domain/errors/ai-generation-failed.error";
import { AIUnavailableError } from "@/common/domain/errors/ai-unavailable.error";
import { DomainError } from "@/common/domain/errors/domain-error";
import { InvalidValueObjectError } from "@/common/domain/errors/invalid-value-object.error";
import {
  ActivityAccessDeniedError,
  ActivityAssignmentNotFoundError,
  ActivityAssignmentNotOwnedError,
  ActivityGroupNotFoundError,
  ActivityNotAssignedToGroupError,
  ActivityNotAvailableError,
  ActivityNotFoundError,
  ActivityNotOwnedError,
  ActivityNotYetVisibleError,
  ActivitySubmissionAlreadyCompletedError,
  ActivitySubmissionNotFoundError,
  ActivitySubmissionNotOwnedError,
  ActivitySubmissionNotSubmittedError,
  InvalidActivitySubmissionScoreError,
  StudentRoleRequiredError,
} from "@/features/activities/domain/activities.errors";
import {
  EmailDomainNotAllowedError,
  ForbiddenPermissionError,
  GoogleEmailNotVerifiedError,
  GoogleSignInNotConfiguredError,
  InvalidBridgeSecretError,
  InvalidCredentialsError,
  InvalidGoogleTokenError,
  InvalidTokenError,
  PasswordLoginNotAvailableError,
  RefreshTokenExpiredError,
  RefreshTokenInvalidError,
  RefreshTokenRevokedError,
  TokenExpiredError,
  UnauthorizedError,
  UserInactiveError,
} from "@/features/auth/domain/auth.errors";
import {
  ClinicalCaseNotFoundError,
  ClinicalCaseUnavailableError,
  ExpertConfigurationMissingError,
} from "@/features/clinical-cases/domain/clinical-cases.errors";
import { CurriculumNodeHasStudentDataError } from "@/features/curriculum/domain/curriculum.errors";
import {
  AttemptDeadlinePassedError,
  EvaluationAlreadyAssignedError,
  EvaluationAssignmentClosedError,
  EvaluationAssignmentForbiddenError,
  EvaluationAssignmentHasAttemptsError,
  EvaluationAssignmentNotFoundError,
  EvaluationAttemptNotFoundError,
  EvaluationAttemptNotGradableError,
  EvaluationAttemptNotGradedError,
  EvaluationAttemptNotInProgressError,
  EvaluationAttemptReadOnlyError,
  EvaluationGradingForbiddenError,
  EvaluationHasSubmittedAttemptsError,
  EvaluationManagementForbiddenError,
  EvaluationMediaNotFoundError,
  EvaluationNotActivatableError,
  EvaluationNotFoundError,
  EvaluationNotOpenError,
  EvaluationNotReadyError,
  EvaluationOptionsNotAllowedError,
  EvaluationQuestionNotFoundError,
  EvaluationQuestionOptionNotFoundError,
  EvaluationReferenceNotFoundError,
  EvaluationScenarioNotFoundError,
  GradeFeedbackAttemptNotGradedError,
  GradeFeedbackForbiddenError,
  GradeFeedbackNotAvailableError,
  GradeOverrideCommentRequiredError,
  InvalidEvaluationAnswerError,
  InvalidEvaluationAssignmentGroupError,
  InvalidEvaluationAssignmentWindowError,
  InvalidEvaluationReorderError,
  InvalidEvaluationRichTextError,
  InvalidEvaluationStatusTransitionError,
  InvalidManualScoreError,
  MaxAttemptsReachedError,
} from "@/features/evaluation/domain/evaluation.errors";
import {
  GroupFullError,
  GroupHasSubgroupsError,
  GroupLeaderNotAllowedError,
  GroupManagementForbiddenError,
  GroupMaxDepthExceededError,
  GroupMemberNotFoundError,
  GroupMemberRoleNotAllowedError,
  GroupNotFoundError,
  GroupSupervisionNotFoundError,
  GroupTypeCreationForbiddenError,
  GroupUserNotFoundError,
  InvalidGroupSupervisionError,
  ParentGroupInactiveError,
  ParentGroupNotFoundError,
  SimulatorLeadNotMemberError,
  StudentAlreadyInGroupError,
} from "@/features/groups/domain/groups.errors";
import {
  InactiveModuleLessonCreationError,
  InvalidLessonContentError,
  InvalidLessonReorderError,
  LessonNotFoundError,
  LessonOrderAlreadyTakenError,
} from "@/features/lessons/domain/lessons.errors";
import {
  InvalidLevelReorderError,
  LevelCircularDependencyError,
  LevelNotFoundError,
  LevelOrderAlreadyTakenError,
  LevelPrerequisiteAlreadyExistsError,
  LevelPrerequisiteNotFoundError,
  LevelSelfPrerequisiteError,
  LevelTitleAlreadyExistsError,
  ParentLevelNotFoundError,
  PrerequisiteLevelNotFoundError,
} from "@/features/levels/domain/levels.errors";
import {
  MediaFileRequiredError,
  MediaInUseError,
  MediaNotFoundError,
  MediaStorageUnavailableError,
  MediaTooLargeError,
  UnsupportedMediaTypeError,
} from "@/features/media/domain/media.errors";
import {
  InvalidModulePrerequisitesError,
  InvalidModuleReorderError,
  ModuleCircularDependencyError,
  ModuleHasNoLessonsError,
  ModuleInactiveError,
  ModuleNodeLevelRequiredError,
  ModuleNotFoundError,
  ModuleOrderAlreadyTakenError,
  ModulePrerequisiteAlreadyExistsError,
  ModulePrerequisiteNotFoundError,
  ModuleSelfPrerequisiteError,
  ModuleTitleAlreadyExistsError,
  PrerequisiteModuleNotFoundError,
} from "@/features/modules/domain/modules.errors";
import {
  InvalidNoteContentError,
  InvalidNotesAnalysisScopeError,
  NoNotesToAnalyzeError,
  NoteLessonNotFoundError,
  NoteModuleNotFoundError,
  NoteNotFoundError,
  NotePageNotInLessonError,
  NotesAnalysisInvalidResponseError,
} from "@/features/notes/domain/notes.errors";
import {
  CannotManageOverridesError,
  ContentOverrideAlreadyExistsError,
  ContentOverrideNotFoundError,
  InvalidOverrideDataError,
  OverrideTargetNotFoundError,
} from "@/features/overrides/domain/overrides.errors";
import {
  InvalidPageBlockError,
  InvalidPageBlockReorderError,
  InvalidPageReorderError,
  PageBlockNotFoundError,
  PageMediaNotFoundError,
  PageNotFoundError,
  PageSlugAlreadyExistsError,
} from "@/features/pages/domain/pages.errors";
import {
  LessonAccessDeniedError,
  QuizScoreRequiredError,
} from "@/features/progress/domain/progress.errors";
import { QuizAlreadyAttemptedError, QuizInactiveError, QuizNotFoundError } from "@/features/quizzes/domain/quizzes.errors";
import { InvalidScorePointsError, ScoreNotFoundError, ScoreNotOwnedError } from "@/features/scores/domain/scores.errors";
import { InvalidSectionReorderError, SectionNotFoundError, SectionSlugAlreadyExistsError } from "@/features/sections/domain/sections.errors";
import {
  InvalidVentilatorCommandError,
  NoActiveReservationError,
  NotReservationLeaderError,
  PatientDataRequiredError,
  PatientNotConfiguredError,
  SimulationCaseNotFoundError,
  VentilatorAlreadyReservedError,
  VentilatorNotConnectedError,
} from "@/features/simulation/domain/simulation.errors";
import {
  InactiveLessonStepCreationError,
  InvalidStepReorderError,
  StepNotFoundError,
  StepOrderAlreadyTakenError,
} from "@/features/steps/domain/steps.errors";
import {
  TeacherRoleRequiredError,
  TeacherStudentAlreadyExistsError,
  TeacherStudentNotFoundError,
} from "@/features/teacher-students/domain/teacher-students.errors";
import {
  CannotChangeOwnRoleError,
  CannotChangeOwnStatusError,
  InvalidCurrentPasswordError,
  PasswordNotSetError,
  SamePasswordError,
  StudentAccessDeniedError,
  SuperadminRoleImmutableError,
  SuperadminStatusImmutableError,
  UserAlreadyExistsError,
  UserNotFoundError,
  UserNotStudentError,
} from "@/features/users/domain/users.errors";

export const DOMAIN_ERROR_STATUS_MAP: Map<new (...args: any[]) => DomainError, HttpStatus> = new Map<
  new (...args: any[]) => DomainError,
  HttpStatus
>([
  [InvalidValueObjectError, HttpStatus.BAD_REQUEST],
  [AIUnavailableError, HttpStatus.SERVICE_UNAVAILABLE],
  [AIGenerationFailedError, HttpStatus.BAD_GATEWAY],
  [InvalidCredentialsError, HttpStatus.UNAUTHORIZED],
  [UnauthorizedError, HttpStatus.UNAUTHORIZED],
  [TokenExpiredError, HttpStatus.UNAUTHORIZED],
  [InvalidTokenError, HttpStatus.UNAUTHORIZED],
  [RefreshTokenExpiredError, HttpStatus.UNAUTHORIZED],
  [RefreshTokenInvalidError, HttpStatus.UNAUTHORIZED],
  [InvalidBridgeSecretError, HttpStatus.UNAUTHORIZED],
  [RefreshTokenRevokedError, HttpStatus.UNAUTHORIZED],
  [UserInactiveError, HttpStatus.FORBIDDEN],
  [PasswordLoginNotAvailableError, HttpStatus.BAD_REQUEST],
  [GoogleSignInNotConfiguredError, HttpStatus.SERVICE_UNAVAILABLE],
  [InvalidGoogleTokenError, HttpStatus.UNAUTHORIZED],
  [GoogleEmailNotVerifiedError, HttpStatus.UNAUTHORIZED],
  [EmailDomainNotAllowedError, HttpStatus.FORBIDDEN],
  [ForbiddenPermissionError, HttpStatus.FORBIDDEN],
  [GroupNotFoundError, HttpStatus.NOT_FOUND],
  [ParentGroupNotFoundError, HttpStatus.BAD_REQUEST],
  [ParentGroupInactiveError, HttpStatus.BAD_REQUEST],
  [GroupMaxDepthExceededError, HttpStatus.BAD_REQUEST],
  [GroupHasSubgroupsError, HttpStatus.CONFLICT],
  [GroupFullError, HttpStatus.CONFLICT],
  [GroupMemberNotFoundError, HttpStatus.NOT_FOUND],
  [SimulatorLeadNotMemberError, HttpStatus.BAD_REQUEST],
  [GroupMemberRoleNotAllowedError, HttpStatus.UNPROCESSABLE_ENTITY],
  [StudentAlreadyInGroupError, HttpStatus.CONFLICT],
  [GroupLeaderNotAllowedError, HttpStatus.UNPROCESSABLE_ENTITY],
  [GroupManagementForbiddenError, HttpStatus.FORBIDDEN],
  [GroupTypeCreationForbiddenError, HttpStatus.FORBIDDEN],
  [InvalidGroupSupervisionError, HttpStatus.UNPROCESSABLE_ENTITY],
  [GroupSupervisionNotFoundError, HttpStatus.NOT_FOUND],
  [GroupUserNotFoundError, HttpStatus.NOT_FOUND],
  [ScoreNotFoundError, HttpStatus.NOT_FOUND],
  [ScoreNotOwnedError, HttpStatus.FORBIDDEN],
  [InvalidScorePointsError, HttpStatus.BAD_REQUEST],
  [TeacherStudentNotFoundError, HttpStatus.NOT_FOUND],
  [TeacherStudentAlreadyExistsError, HttpStatus.CONFLICT],
  [TeacherRoleRequiredError, HttpStatus.BAD_REQUEST],
  [UserNotFoundError, HttpStatus.NOT_FOUND],
  [UserAlreadyExistsError, HttpStatus.CONFLICT],
  [InvalidCurrentPasswordError, HttpStatus.BAD_REQUEST],
  [PasswordNotSetError, HttpStatus.BAD_REQUEST],
  [SamePasswordError, HttpStatus.BAD_REQUEST],
  [UserNotStudentError, HttpStatus.BAD_REQUEST],
  [StudentAccessDeniedError, HttpStatus.FORBIDDEN],
  [CannotChangeOwnRoleError, HttpStatus.BAD_REQUEST],
  [SuperadminRoleImmutableError, HttpStatus.FORBIDDEN],
  [SuperadminStatusImmutableError, HttpStatus.FORBIDDEN],
  [CannotChangeOwnStatusError, HttpStatus.BAD_REQUEST],
  [LevelNotFoundError, HttpStatus.NOT_FOUND],
  [PrerequisiteLevelNotFoundError, HttpStatus.NOT_FOUND],
  [ParentLevelNotFoundError, HttpStatus.NOT_FOUND],
  [LevelTitleAlreadyExistsError, HttpStatus.CONFLICT],
  [LevelOrderAlreadyTakenError, HttpStatus.CONFLICT],
  [InvalidLevelReorderError, HttpStatus.BAD_REQUEST],
  [LevelSelfPrerequisiteError, HttpStatus.BAD_REQUEST],
  [LevelCircularDependencyError, HttpStatus.CONFLICT],
  [LevelPrerequisiteAlreadyExistsError, HttpStatus.CONFLICT],
  [LevelPrerequisiteNotFoundError, HttpStatus.NOT_FOUND],
  [ModuleNotFoundError, HttpStatus.NOT_FOUND],
  [PrerequisiteModuleNotFoundError, HttpStatus.NOT_FOUND],
  [ModuleTitleAlreadyExistsError, HttpStatus.CONFLICT],
  [ModuleOrderAlreadyTakenError, HttpStatus.CONFLICT],
  [InvalidModulePrerequisitesError, HttpStatus.BAD_REQUEST],
  [InvalidModuleReorderError, HttpStatus.BAD_REQUEST],
  [ModuleSelfPrerequisiteError, HttpStatus.BAD_REQUEST],
  [ModuleCircularDependencyError, HttpStatus.CONFLICT],
  [ModulePrerequisiteAlreadyExistsError, HttpStatus.CONFLICT],
  [ModulePrerequisiteNotFoundError, HttpStatus.NOT_FOUND],
  [ModuleInactiveError, HttpStatus.BAD_REQUEST],
  [ModuleHasNoLessonsError, HttpStatus.BAD_REQUEST],
  [ModuleNodeLevelRequiredError, HttpStatus.BAD_REQUEST],
  [LessonNotFoundError, HttpStatus.NOT_FOUND],
  [InactiveModuleLessonCreationError, HttpStatus.BAD_REQUEST],
  [InvalidLessonContentError, HttpStatus.BAD_REQUEST],
  [LessonOrderAlreadyTakenError, HttpStatus.CONFLICT],
  [InvalidLessonReorderError, HttpStatus.BAD_REQUEST],
  [StepNotFoundError, HttpStatus.NOT_FOUND],
  [InactiveLessonStepCreationError, HttpStatus.BAD_REQUEST],
  [StepOrderAlreadyTakenError, HttpStatus.CONFLICT],
  [InvalidStepReorderError, HttpStatus.BAD_REQUEST],
  [PageNotFoundError, HttpStatus.NOT_FOUND],
  [PageSlugAlreadyExistsError, HttpStatus.CONFLICT],
  [InvalidPageBlockError, HttpStatus.BAD_REQUEST],
  [PageBlockNotFoundError, HttpStatus.NOT_FOUND],
  [PageMediaNotFoundError, HttpStatus.BAD_REQUEST],
  [InvalidPageReorderError, HttpStatus.BAD_REQUEST],
  [InvalidPageBlockReorderError, HttpStatus.BAD_REQUEST],
  [SectionNotFoundError, HttpStatus.NOT_FOUND],
  [SectionSlugAlreadyExistsError, HttpStatus.CONFLICT],
  [InvalidSectionReorderError, HttpStatus.BAD_REQUEST],
  [CurriculumNodeHasStudentDataError, HttpStatus.CONFLICT],
  [ContentOverrideNotFoundError, HttpStatus.NOT_FOUND],
  [CannotManageOverridesError, HttpStatus.FORBIDDEN],
  [OverrideTargetNotFoundError, HttpStatus.NOT_FOUND],
  [InvalidOverrideDataError, HttpStatus.BAD_REQUEST],
  [ContentOverrideAlreadyExistsError, HttpStatus.CONFLICT],
  [LessonAccessDeniedError, HttpStatus.FORBIDDEN],
  [QuizScoreRequiredError, HttpStatus.BAD_REQUEST],
  [QuizNotFoundError, HttpStatus.NOT_FOUND],
  [QuizInactiveError, HttpStatus.FORBIDDEN],
  [QuizAlreadyAttemptedError, HttpStatus.CONFLICT],
  [ClinicalCaseNotFoundError, HttpStatus.NOT_FOUND],
  [ClinicalCaseUnavailableError, HttpStatus.FORBIDDEN],
  [ExpertConfigurationMissingError, HttpStatus.UNPROCESSABLE_ENTITY],
  [ActivityNotFoundError, HttpStatus.NOT_FOUND],
  [ActivityNotOwnedError, HttpStatus.FORBIDDEN],
  [ActivityAccessDeniedError, HttpStatus.FORBIDDEN],
  [ActivityNotAvailableError, HttpStatus.FORBIDDEN],
  [ActivityNotAssignedToGroupError, HttpStatus.FORBIDDEN],
  [ActivityNotYetVisibleError, HttpStatus.FORBIDDEN],
  [ActivityGroupNotFoundError, HttpStatus.NOT_FOUND],
  [ActivityAssignmentNotFoundError, HttpStatus.NOT_FOUND],
  [ActivityAssignmentNotOwnedError, HttpStatus.FORBIDDEN],
  [ActivitySubmissionNotFoundError, HttpStatus.NOT_FOUND],
  [ActivitySubmissionNotOwnedError, HttpStatus.FORBIDDEN],
  [ActivitySubmissionAlreadyCompletedError, HttpStatus.CONFLICT],
  [ActivitySubmissionNotSubmittedError, HttpStatus.BAD_REQUEST],
  [InvalidActivitySubmissionScoreError, HttpStatus.BAD_REQUEST],
  [StudentRoleRequiredError, HttpStatus.FORBIDDEN],
  [VentilatorAlreadyReservedError, HttpStatus.CONFLICT],
  [NoActiveReservationError, HttpStatus.NOT_FOUND],
  [InvalidVentilatorCommandError, HttpStatus.UNPROCESSABLE_ENTITY],
  [NotReservationLeaderError, HttpStatus.FORBIDDEN],
  [VentilatorNotConnectedError, HttpStatus.SERVICE_UNAVAILABLE],
  [PatientDataRequiredError, HttpStatus.BAD_REQUEST],
  [PatientNotConfiguredError, HttpStatus.NOT_FOUND],
  [SimulationCaseNotFoundError, HttpStatus.NOT_FOUND],
  [MediaNotFoundError, HttpStatus.NOT_FOUND],
  [MediaInUseError, HttpStatus.CONFLICT],
  [MediaStorageUnavailableError, HttpStatus.SERVICE_UNAVAILABLE],
  [UnsupportedMediaTypeError, HttpStatus.UNSUPPORTED_MEDIA_TYPE],
  [MediaTooLargeError, HttpStatus.PAYLOAD_TOO_LARGE],
  [MediaFileRequiredError, HttpStatus.BAD_REQUEST],
  [NoteNotFoundError, HttpStatus.NOT_FOUND],
  [NoteLessonNotFoundError, HttpStatus.NOT_FOUND],
  [NoteModuleNotFoundError, HttpStatus.NOT_FOUND],
  [NotePageNotInLessonError, HttpStatus.BAD_REQUEST],
  [InvalidNoteContentError, HttpStatus.BAD_REQUEST],
  [InvalidNotesAnalysisScopeError, HttpStatus.BAD_REQUEST],
  [NoNotesToAnalyzeError, HttpStatus.UNPROCESSABLE_ENTITY],
  [NotesAnalysisInvalidResponseError, HttpStatus.BAD_GATEWAY],
  [EvaluationNotFoundError, HttpStatus.NOT_FOUND],
  [EvaluationScenarioNotFoundError, HttpStatus.NOT_FOUND],
  [EvaluationQuestionNotFoundError, HttpStatus.NOT_FOUND],
  [EvaluationQuestionOptionNotFoundError, HttpStatus.NOT_FOUND],
  [EvaluationManagementForbiddenError, HttpStatus.FORBIDDEN],
  [EvaluationHasSubmittedAttemptsError, HttpStatus.CONFLICT],
  [InvalidEvaluationStatusTransitionError, HttpStatus.CONFLICT],
  [EvaluationNotReadyError, HttpStatus.UNPROCESSABLE_ENTITY],
  [EvaluationOptionsNotAllowedError, HttpStatus.UNPROCESSABLE_ENTITY],
  [EvaluationMediaNotFoundError, HttpStatus.UNPROCESSABLE_ENTITY],
  [EvaluationReferenceNotFoundError, HttpStatus.UNPROCESSABLE_ENTITY],
  [InvalidEvaluationReorderError, HttpStatus.BAD_REQUEST],
  [InvalidEvaluationRichTextError, HttpStatus.BAD_REQUEST],
  [EvaluationAssignmentNotFoundError, HttpStatus.NOT_FOUND],
  [EvaluationAssignmentForbiddenError, HttpStatus.FORBIDDEN],
  [EvaluationNotActivatableError, HttpStatus.CONFLICT],
  [InvalidEvaluationAssignmentGroupError, HttpStatus.UNPROCESSABLE_ENTITY],
  [InvalidEvaluationAssignmentWindowError, HttpStatus.UNPROCESSABLE_ENTITY],
  [EvaluationAlreadyAssignedError, HttpStatus.CONFLICT],
  [EvaluationAssignmentClosedError, HttpStatus.CONFLICT],
  [EvaluationAssignmentHasAttemptsError, HttpStatus.CONFLICT],
  [EvaluationNotOpenError, HttpStatus.FORBIDDEN],
  [MaxAttemptsReachedError, HttpStatus.CONFLICT],
  [AttemptDeadlinePassedError, HttpStatus.CONFLICT],
  [EvaluationAttemptNotFoundError, HttpStatus.NOT_FOUND],
  [EvaluationAttemptNotInProgressError, HttpStatus.CONFLICT],
  [EvaluationAttemptReadOnlyError, HttpStatus.CONFLICT],
  [InvalidEvaluationAnswerError, HttpStatus.UNPROCESSABLE_ENTITY],
  [EvaluationGradingForbiddenError, HttpStatus.FORBIDDEN],
  [EvaluationAttemptNotGradableError, HttpStatus.CONFLICT],
  [EvaluationAttemptNotGradedError, HttpStatus.CONFLICT],
  [InvalidManualScoreError, HttpStatus.UNPROCESSABLE_ENTITY],
  [GradeOverrideCommentRequiredError, HttpStatus.UNPROCESSABLE_ENTITY],
  [GradeFeedbackNotAvailableError, HttpStatus.NOT_FOUND],
  [GradeFeedbackAttemptNotGradedError, HttpStatus.CONFLICT],
  [GradeFeedbackForbiddenError, HttpStatus.FORBIDDEN],
]);
